### PR TITLE
new artifact JBPM Server Distribution.zip

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mswiderski** [comment]
@mbiarnes isn't it the same thing as this one https://github.com/kiegroup/jbpm-website/blob/9b463a279914b37ac6e195cf5d51c4638ab7cdc5/_config/pom.yml#L5

**Comment by mbiarnes** [comment]
> @mbiarnes isn't it the same thing as this one
> 
> [jbpm-website/_config/pom.yml](https://github.com/kiegroup/jbpm-website/blob/9b463a279914b37ac6e195cf5d51c4638ab7cdc5/_config/pom.yml#L5)
> 
> Line 5 in [9b463a2](/kiegroup/jbpm-website/commit/9b463a279914b37ac6e195cf5d51c4638ab7cdc5)
>  jbpmServerZip: https://download.jboss.org/jbpm/release/7.15.0.Final/jbpm-server-7.15.0.Final-dist.zip

fixed

**Comment by mswiderski** [comment]
@mbiarnes why is this needed? The server zip download has its own section at the top of the download page, the list of other downloads is next so don't see I point of repeating it again... or am I missing something?

**Comment by mbiarnes** [comment]
@mswiderski you're right - this is obsolete - I will close this PR

**Pull request closed without merging**
