### PR TITLE
Migration to JBake

### PR DESCRIPTION
**Pull request by hbelmiro**
This PR migrates the jBPM website to JBake.
I didn't do any changes related to CI. If anything else is needed, please let me know.
Also, there are some files that I didn't remove because I don't know if they are related to CI or not.

### CODE REVIEW

**Review by LightGuard — APPROVED** [review]

**Comment by hbelmiro** [comment]
@mbiarnes Should I do anything regarding to the failing check?

> Error /github/workspace/_config does not exist.

The equivalent directory to `_config` now is `data`.

**Review by mbiarnes — COMMENTED** [review]
@hbelmiro please look at https://github.com/hbelmiro/jbpm-website/pull/1 - this one has to be merged fist. Important: after these PRs are merged it also has to be merged https://github.com/kiegroup/kie-jenkins-scripts/pull/1266 since with the changes it will not work anymore the Dockerfile

**Comment by mbiarnes** [comment]
@hbelmiro 
Can you please check the conflicting files?
 _config/
_layouts/
_partials/ can simply be removed I think since they don't exist anymore but
as well as community/team.html.haml

The only file where I get conficts (the reason why I didn't follow the command line instructions) was data/users.yml.

**Comment by hbelmiro** [comment]
@mbiarnes Yes. I'm integrating the changes that were committed after my PR. It's not just a rebase. I need to convert them to JBake.
Once I finish this, I'll approve https://github.com/kiegroup/kie-jenkins-scripts/pull/1266.

**Comment by mbiarnes** [comment]
> 

@hbelmiro great

**Comment by hbelmiro** [comment]
@mbiarnes 

- [x] [PR1](https://github.com/hbelmiro/jbpm-website/pull/1) merged into this one
- [x] Recent commits integrated to this PR
- [x] Conflicts fixed
- [x] [PR3](https://github.com/kiegroup/kie-jenkins-scripts/pull/1266) approved

I don't have permission to merge them. Can you please merge or give me permission?

**Comment by mbiarnes** [comment]
@hbelmiro sure - once this URL check is green

**Comment by mbiarnes** [comment]
@hbelmiro got it. 
Is is possible to change https://github.com/kiegroup/jbpm-website/blob/main/.github/workflows/check-url.yml#L22 `_config` to `data`? `_config` is not anymore existing, and the URL checker seeks this directory. I think now all is underneath `data`

**Pull request merged**
