### PR TITLE
JBPM-7841 - Add Controller Swagger docs

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by mswiderski** [comment]
@cristianonicolai how did you generate the asciidoc? could be worth using https://github.com/mswiderski/swagger-docs-generator as it will include the examples and ToC for the paths document.

**Comment by cristianonicolai** [comment]
@mswiderski I used your fork here https://github.com/mswiderski/swagger2markup to execute the export with the fix in place. 
`URL remoteSwaggerFile = new URL("http://localhost:8080/controller/rest/swagger.json");
            Path outputDirectory = Paths.get("build/asciidoc");

            Swagger2MarkupConverter.from(remoteSwaggerFile)
                    .build()
                    .toFolder(outputDirectory);`

**Comment by mswiderski** [comment]
then you miss a but of config, see here https://github.com/mswiderski/swagger-docs-generator/blob/master/src/main/java/org/kie/server/docs/generator/GenerateDocs.java and then the ToC is added by the extension https://github.com/mswiderski/swagger-docs-generator/blob/master/src/main/java/org/kie/server/docs/generator/AddExamplePathsDocumentExtension.java#L42

**Comment by cristianonicolai** [comment]
@mswiderski oh ok, let me do it again using your project.

**Comment by cristianonicolai** [comment]
@mswiderski done

**Comment by cristianonicolai** [comment]
@mswiderski I've updated this PR based on the last discussions in https://github.com/kiegroup/droolsjbpm-integration/pull/1610

**Pull request merged**
