### PR TITLE
7.11 release update

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by mbiarnes** [comment]
@cristianonicolai all good except the release date - 7.11.0.Final was not yet released - it is in the internal sanity check phase

**Comment by cristianonicolai** [comment]
@mbiarnes that's fine, I will get it changed once the release is done.

**Comment by mbiarnes** [comment]
@cristianonicolai so this will be merged once the 7.11.0.Final is out and released and the binaries pushed to filemgmt.jboss.org

**Comment by cristianonicolai** [comment]
@mbiarnes date updated.

**Pull request merged**
